### ISSUE TITLE
How is the 15k limit counted?

### ISSUE THREAD

**Issue by leonardodino** [freegeoipapp/freegeoip#2]
Hey @freegeoipapp,

How are the **15,000** queries per hour counted?
There seems to be no way of passing API key.

**Comment by freegeoipapp** [comment]
The limit is counted by the requesting IP address.

See the response headers:
x-ratelimit-limit: 15000
x-ratelimit-remaining: 14998
x-ratelimit-reset: 2539

**Comment by leonardodino** [comment]
Thanks! 🙂
